# Generated by Django 4.1.3 on 2022-12-08 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0005_remove_confirmorder_пользователь_confirmorder_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="paid", new_name="confirm",
        ),
        migrations.RemoveField(model_name="confirmorder", name="paid",),
        migrations.AddField(
            model_name="confirmorder",
            name="status",
            field=models.CharField(
                choices=[
                    ("Оплачен", "Оплачен"),
                    ("Доставлен", "Доставлен"),
                    ("Доставляется", "Доставляется"),
                    ("Возврат", "Возврат"),
                ],
                default="Оплачен",
                max_length=50,
                verbose_name="Статус",
            ),
        ),
    ]
