# Generated by Django 4.1.3 on 2022-12-08 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0009_alter_order_total_price_alter_orderitem_price"),
    ]

    operations = [
        migrations.RemoveField(model_name="confirmorder", name="total_price",),
        migrations.RemoveField(model_name="order", name="total_price",),
    ]
