# Generated by Django 4.1.3 on 2022-12-08 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0010_remove_confirmorder_total_price_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="confirmorder",
            name="total_price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=20, verbose_name="Сумма"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="order",
            name="totla_price",
            field=models.DecimalField(
                decimal_places=2, default=1, max_digits=20, verbose_name="Сумма"
            ),
            preserve_default=False,
        ),
    ]
