# Generated by Django 4.1.3 on 2022-12-08 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0011_confirmorder_total_price_order_totla_price"),
    ]

    operations = [
        migrations.RenameField(
            model_name="order", old_name="totla_price", new_name="total_price",
        ),
    ]
