# Generated by Django 4.1.3 on 2022-12-08 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0012_rename_totla_price_order_total_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="confirmorder",
            options={
                "ordering": ("created_date",),
                "verbose_name": "Подтвержденный заказ",
                "verbose_name_plural": "Подтвержденные заказы",
            },
        ),
        migrations.AlterModelOptions(
            name="order",
            options={
                "ordering": ("created_date",),
                "verbose_name": "Заказ",
                "verbose_name_plural": "Заказы",
            },
        ),
    ]
