# Generated by Django 4.1.3 on 2022-12-08 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0014_orderitem_status_alter_orderitem_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="orderitem",
            name="status",
            field=models.CharField(
                default="Оплачен", max_length=50, verbose_name="Статус"
            ),
        ),
    ]
